title: Eli Lestari # your name (or website title) here
logo: "/images/logo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Saya adalah seorang praktisi data yang berpengalaman dalam menafsirkan dan menganalisis data untuk mendorong pertumbuhan bisnis. Dapat memberikan wawasan, analitik, dan kecerdasan bisnis yang diperlukan untuk pengambilan keputusan. 
  <br><br>
  
  <a href="https://github.com/elilestari">View My Github Profile</a>
  <br>
  <a href="https://www.linkedin.com/in/eli-lestari-b69809174/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.instagram.com/eli_lstr/">View My Instagram Profile</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
